# Generated by Django 4.1.1 on 2022-09-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiculture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='issue_id',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='assignee_user_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='author_user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='author_user_id',
            new_name='author',
        ),
    ]
