# Generated by Django 4.1.1 on 2022-09-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiculture', '0002_rename_author_user_id_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
