# Generated by Django 4.1.1 on 2022-09-30 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiculture', '0004_remove_comment_comment_id_remove_issue_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.AddField(
            model_name='contributor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiculture.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiculture.contributor'),
            preserve_default=False,
        ),
    ]
