# Generated by Django 4.1.1 on 2022-09-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiculture', '0005_remove_contributor_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project',
        ),
        migrations.AddField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiculture.project'),
            preserve_default=False,
        ),
    ]
